---

sudo: false

language: python
cache: pip

before_script:
  - pip install tox

script: tox

install: true

notifications:
  email: false

matrix:
  fast_finish: true
  include:

    # Dashboard

    - python: "2.7"
      env: TOXENV=py27

    - python: "3.6"
      env: TOXENV=py36

    # MCPServer

    - python: "2.7"
      env: TOXENV=mcpserver

    - python: "3.6"
      env: TOXENV=mcpserver

    # Linters

    - python: "2.7"
      env: TOXENV=py27-flake8

    - python: "3.6"
      env: TOXENV=py36-flake8

  allow_failures:

    - python: "3.6"
      env: TOXENV=py36

    - python: "3.6"
      env: TOXENV=mcpserver
